FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Product Catalog

Polls is a simple API allowing consumers to view polls and vote in them.

## ProductCatalogs Collection [/products]

### List All ProductCatalogs [GET]

+ Response 200 (application/json)

        [
            {
                "productItemCode" : 1,
                "productItemName": "",
                "divisionCode": "",
                "divisionName": ""
            },
            {
                "productItemCode" : 2,
                "productItemName": "",
                "divisionCode": "",
                "divisionName": ""
            }
        ]