FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Product Catalog

Polls is a simple API allowing consumers to view polls and vote in them.

## ProductCatalogs Collection [/products]

### List All ProductCatalogs [GET]

+ Response 200 (application/json)

        [
            {
                "productItemCode" : 1,
                "productItemName": "Dầu Gội XMen",
                "divisionCode": 1,
                "divisionName": "",
                "categoryCode": 1,
                "categoryName": "",
                "description": "",
                "imageUrl": ""
                "caseFormat": 
                {
                    "formatCode": 1,
                    "formatName": "product case format",
                    "unit": 
                    {
                        "unitCode": 1,
                        "unitName": "product case unit",
                        "conversion": 10
                    },
                    "price": 
                    [
                        {
                            "priceCode": 1,
                            "priceName": "price for retailer",
                            "priceGroupCode": 1,
                            "priceGroupName": ""
                            "amount": 12,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 2,
                            "priceName": "price for customer",
                            "priceGroupCode": 2,
                            "priceGroupName": ""
                            "amount": 15,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 3,
                            "priceName": "price for distributor",
                            "priceGroupCode": 3,
                            "priceGroupName": ""
                            "amount": 10,
                            "currency": "vnd"
                        }
                    ]
                },
                "bundleFormat": 
                {
                    "formatCode": 2,
                    "formatName": "product bundle format",
                    "unit": 
                    {
                        "unitCode": 2,
                        "unitName": "product bundle unit",
                        "conversion": 5
                    },
                    "price": 
                    [
                        {
                            "priceCode": 4,
                            "priceName": "price for retailer",
                            "priceGroupCode": 1,
                            "priceGroupName": ""
                            "amount": 6,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 5,
                            "priceName": "price for customer",
                            "priceGroupCode": 2,
                            "priceGroupName": ""
                            "amount": 9,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 6,
                            "priceName": "price for distributor",
                            "priceGroupCode": 3,
                            "priceGroupName": ""
                            "amount": 5,
                            "currency": "vnd"
                        }
                    ]
                },
                "upcFormat": 
                {
                    "formatCode": 3,
                    "formatName": "product upc format",
                    "unit": 
                    {
                        "unitCode": 3,
                        "unitName": "product upc unit",
                        "conversion": 1
                    },
                    "price": 
                    [
                        {
                            "priceCode": 7,
                            "priceName": "price for retailer",
                            "priceGroupCode": 1,
                            "priceGroupName": ""
                            "amount": 3,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 8,
                            "priceName": "price for customer",
                            "priceGroupCode": 2,
                            "priceGroupName": ""
                            "amount": 5,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 9,
                            "priceName": "price for distributor",
                            "priceGroupCode": 3,
                            "priceGroupName": ""
                            "amount": 1,
                            "currency": "vnd"
                        }
                    ]
                }
            },
            {
                "productItemCode" : 2,
                "productItemName": "Dầu Gội Dove",
                "divisionCode": 1,
                "divisionName": "",
                "categoryCode": 2,
                "categoryName": "",
                "description": "",
                "imageUrl": ""
                "caseFormat": 
                {
                    "formatCode": 4,
                    "formatName": "product case format",
                    "unit": 
                    {
                        "unitCode": 4,
                        "unitName": "product case unit",
                        "conversion": 15
                    },
                    "price": 
                    [
                        {
                            "priceCode": 10,
                            "priceName": "price for retailer",
                            "priceGroupCode": 1,
                            "priceGroupName": ""
                            "amount": 12,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 11,
                            "priceName": "price for customer",
                            "priceGroupCode": 2,
                            "priceGroupName": ""
                            "amount": 15,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 12,
                            "priceName": "price for distributor",
                            "priceGroupCode": 3,
                            "priceGroupName": ""
                            "amount": 10,
                            "currency": "vnd"
                        }
                    ]
                },
                "bundleFormat": 
                {
                    "formatCode": 5,
                    "formatName": "product bundle format",
                    "unit": 
                    {
                        "unitCode": 5,
                        "unitName": "product bundle unit",
                        "conversion": 4
                    },
                    "price": 
                    [
                        {
                            "priceCode": 13,
                            "priceName": "price for retailer",
                            "priceGroupCode": 1,
                            "priceGroupName": ""
                            "amount": 6,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 14,
                            "priceName": "price for customer",
                            "priceGroupCode": 2,
                            "priceGroupName": ""
                            "amount": 9,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 15,
                            "priceName": "price for distributor",
                            "priceGroupCode": 3,
                            "priceGroupName": ""
                            "amount": 5,
                            "currency": "vnd"
                        }
                    ]
                },
                "upcFormat": 
                {
                    "formatCode": 6,
                    "formatName": "product upc format",
                    "unit": 
                    {
                        "unitCode": 6,
                        "unitName": "product upc unit",
                        "conversion": 1
                    },
                    "price": 
                    [
                        {
                            "priceCode": 16,
                            "priceName": "price for retailer",
                            "priceGroupCode": 1,
                            "priceGroupName": ""
                            "amount": 3,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 17,
                            "priceName": "price for customer",
                            "priceGroupCode": 2,
                            "priceGroupName": ""
                            "amount": 5,
                            "currency": "vnd"
                        },
                        {
                            "priceCode": 18,
                            "priceName": "price for distributor",
                            "priceGroupCode": 3,
                            "priceGroupName": ""
                            "amount": 1,
                            "currency": "vnd"
                        }
                    ]
                }
            }
        ]